name: ci

on:
  - push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test
  automerge:
    runs-on: macos-latest
    steps:
      - name: automerge
        uses: mhristof/github-action-automerge@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
